# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'input new release tag'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    permissions:
        contents: write

    steps:

      - uses: actions/checkout@v4
        with:
          repository: PythonSwiftLink/Python-Apple-support
          ref: 3.10
          path: PythonApple

      - name: make python iOS
        working-directory: ./PythonApple
        run: make iOS

      - name: make python macOS
        working-directory: ./PythonApple
        run: make macOS
            

    
