# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'input new release tag'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    permissions:
        contents: write

    steps:

      - name: Git Clone Action

        uses: sudosubin/git-clone-action@v1.0.1
        with:
          # Repository owner and name. Ex: sudosubin/git-clone-action
          repository: PythonSwiftLink/Python-Apple-support
          # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
          # Git branch or tag to checkout.
          ref: "3.10"
          # Relative path from current directory, where to clone.
          path: PythonApple

      - name: make python iOS
        working-directory: ./PythonApple
        run: make iOS

      - name: make python macOS
        working-directory: ./PythonApple
        run: make macOS
            

    
